# Use the official Jupyter Notebook image with scientific Python libraries
FROM jupyter/scipy-notebook

# Copy your notebooks into the working directory
COPY ./notebooks /home/jovyan/work

# Expose Jupyter's default port
EXPOSE 8888
